// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooopedvymtbnzqmxfljq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vb3BlZHZ5bXRibnpxbXhmbGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDA4MjQsImV4cCI6MjA3MjU3NjgyNH0.VnT27Y1w_Psqhnn9bxBrnVyqJJw0v93NqTUM1bzCvO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});